### ISSUE TITLE
Discussion Thread for Several Major Changes

### ISSUE THREAD

**Issue by ltcptgeneral** [titanscout2022/red-alliance-analysis#32]
**Is your feature request related to a problem? Please describe.**
In anticipation of future updates and publishing to distribution, it would be useful to simplify the versioning system both in the future and retrospectively. This should avoid confusion for any new maintainers and users. 

**Describe the solution you'd like**

- Remove the leading digit(s) for all subpackages under `analysis` to simplify them to the usual (but less descriptive) major.minor.patch as described in the Semantic Versioning guidelines. I am still undecided over whether the leading 0 for the patch number should be kept or discarded. This would apply only to those with versioning control already.

- A similar change will be applied to the `superscript.py` file as well, but changing the major number for each version from 0 to 1. This would only apply to `superscript.py` and not `superscript_old.py`.

- All distributions of analysis (aka the wheel files under /analysis-master/dist/) should be retroactively re-versioned in a build.patch fashion. This will also apply to any futre analysis distributions and future superscript application versioning. The current wheel files can be re-versioned by removing the second and third numbers (all currently 0). 

- Find the most convenient way to package superscript most likely as a portable application.

- Creating two new branches (protected) which can automatically build and upload validated versions of analysis and superscript when pushed/merged to. There would also be some small changes to files exclusively in this branch like including twine as a requirement for analysis. 

- In general make versioning across the repo more standardized and easier to read.

**Additional context**
I'll publish a new branch to demo the changes. Discussion is helpful as these are a lot of changes.

**Comment by devksingh4** [comment]
I feel that versioning should go major.minor.patch (Build Number). Opinions?

**Comment by ltcptgeneral** [comment]
I think that major.minor.patch (Build Number) would still be as complex and unnecessary as the current versioning. Plus, none of the things that would be using major.minor.patch would be built individually, so a build/hotfix versioning system would be moot for them.

**Comment by devksingh4** [comment]
I was thinking of this from an API/mobile perspective, so that's fair. In that case, I see no reason why your versioning system won't work. Looking forward to seeing the new branch with the new versioning.
